import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";


const robotoSlab = localFont({
  src: [
    {
      path: './fonts/RobotoSlab-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-Light.ttf',
      weight: '300',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-Medium.ttf',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-SemiBold.ttf',
      weight: '600',
      style: 'normal'
    }
  ],
  variable: '--font-roboto-slab',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={robotoSlab.variable}
      >
        <main className="font-roboto-slab">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
