[build]
  base = "wics-app"
  publish = "out" 
  command = "npm install && npm run build"
  functions = "wics-app/netlify/functions"

[functions]
  directory = "wics-app/netlify/functions"
  node_bundler = "esbuild"
  included_files = ["wics-app/netlify/functions/**/*.ts", "wics-app/netlify/functions/**/*.js"]