name: Debug Dispatch

on:
  repository_dispatch:
    types: [sanity-update]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event Data
        run: |
          echo "Full event payload:"
          echo '${{ toJSON(github.event) }}' | jq .