import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";

import { Roboto_Slab } from "next/font/google";

const font = Roboto_Slab({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Navbar />
                <main className="mx-auto max-w-5xl px-6">{children}</main>
            </body>
        </html>
    );
}
