import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import NavBar from "./components/NavBar";
import NavBar from "@/app/components/NavBar";
import Footer from "./components/Footer";


const robotoSlab = localFont({
  src: [
    {
      path: './fonts/RobotoSlab-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-Light.ttf',
      weight: '300',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-Medium.ttf',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/RobotoSlab-SemiBold.ttf',
      weight: '600',
      style: 'normal'
    }
  ],
  variable: '--font-roboto-slab',
})

export const metadata: Metadata = {
  title: "SFU WiCS",
  description: "Generated by GAHEE",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={robotoSlab.variable}
      >
        <main className="font-roboto-slab min-h-screen flex flex-col">
          <NavBar />

          <div className="container mx-auto pt-24 px-5 flex-1">
            {children}
          </div>

          <div className="pt-12 md:pt-24 lg:pt-40 2xl:pt-64">
            <Footer />
          </div>

          
        </main>
      </body>
    </html>
  );
}
